apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: root
  MONGO_ROOT_PASSWORD: rootpassword
  MONGO_URI: "mongodb://root:rootpassword@mongodb-service:27017/much_todo_db?authSource=admin"