name: Frontend CI/CD

on:
  push:
    branches: [main, feature/backend-only]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci-cd.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy Frontend to S3
        run: |
          aws s3 cp frontend/index.html s3://starttech-frontend-bucket-4944d90c/index.html
          echo "Frontend deployed successfully!"

      - name: Verify Deployment
        run: |
          aws s3 ls s3://starttech-frontend-bucket-4944d90c/
          echo "Deployment verified!"